# Generated by Django 4.1.4 on 2023-05-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_aiportprofile_profile_apron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiportproject',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='editdate'),
        ),
        migrations.AddField(
            model_name='aiportproject',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True, verbose_name='editdate'),
        ),
        migrations.AddField(
            model_name='aiportproject',
            name='edited_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
