# Generated by Django 4.1.4 on 2023-05-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_aiportproject_date_created_aiportproject_date_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiportproject',
            name='agency',
            field=models.CharField(blank=True, choices=[('CAAP APP 2017', 'CAAP APP 2017'), ('CAAP APP 2018', 'CAAP APP 2018'), ('CAAP APP 2019', 'CAAP APP 2019'), ('CAAP APP 2020', 'CAAP APP 2020'), ('CAAP APP 2021', 'CAAP APP 2021'), ('CAAP APP 2022', 'CAAP APP 2022'), ('CAAP APP 2023', 'CAAP APP 2023'), ('DOTr GAA 2015 (downloaded)', 'DOTr GAA 2015 (downloaded)'), ('DOTr GAA 2016 (downloaded)', 'DOTr GAA 2016 (downloaded)'), ('DOTr GAA 2017 (downloaded)', 'DOTr GAA 2017 (downloaded)'), ('DOTr GAA 2018 (downloaded)', 'DOTr GAA 2018 (downloaded)'), ('DOTr GAA 2021 (downloaded)', 'DOTr GAA 2021 (downloaded)'), ('DOTr GAA 2022 (downloaded)', 'DOTr GAA 2022 (downloaded)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='area',
            field=models.CharField(blank=True, choices=[('AREA 1', 'AREA 1'), ('AREA 2', 'AREA 2'), ('AREA 3', 'AREA 3'), ('AREA 4', 'AREA 4'), ('AREA 5', 'AREA 5'), ('AREA 6', 'AREA 6'), ('AREA 7', 'AREA 7'), ('AREA 8', 'AREA 8'), ('AREA 9', 'AREA 9'), ('AREA 10', 'AREA 10'), ('AREA 11', 'AREA 11'), ('AREA 12', 'AREA 12'), ('CATC', 'CATC'), ('HEAD OFFICE', 'HEAD OFFICE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='certificate',
            field=models.CharField(blank=True, choices=[('w/ Certificate of Final Acceptance', 'w/ Certificate of Final Acceptance'), ('w/ Certificate of Final Completion', 'w/ Certificate of Final Completion'), ('w/O Certificate', 'w/O Certificate')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='recouped_pay',
            field=models.CharField(blank=True, choices=[('DONE', 'DONE'), ('NONE', 'NONE'), ('PROCESSING', 'PROCESSING')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='region',
            field=models.CharField(blank=True, choices=[('REGION 1', 'REGION 1'), ('REGION 2', 'REGION 2'), ('REGION 3', 'REGION 3'), ('REGION 4.A', 'REGION 4.A'), ('REGION 4.B', 'REGION 4.B'), ('REGION 5', 'REGION 5'), ('REGION 6', 'REGION 6'), ('REGION 7', 'REGION 7'), ('REGION 8', 'REGION 8'), ('REGION 9', 'REGION 9'), ('REGION 10', 'REGION 10'), ('REGION 11', 'REGION 11'), ('REGION 12', 'REGION 12'), ('REGION 12/BARMM', 'REGION 12/BARMM'), ('CARAGA (REGION 13)', 'CARAGA (REGION 13)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='slippage',
            field=models.CharField(blank=True, choices=[('ANS', 'ANS'), ('Negative', 'Negative'), ('Positive', 'Positive'), ('Pending', 'Pending'), ('Terminated', 'Terminated'), ('Blanks', 'Blanks')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aiportproject',
            name='status',
            field=models.CharField(blank=True, choices=[('Complete', 'Complete'), ('DED', 'DED'), ('On-Going', 'On-Going'), ('Others', 'Others'), ('Process of POW & Plans', 'Process of POW & Plans'), ('SAC', 'SAC'), ('Under Procurement', 'Under Procurement'), ('Blank', 'Blank')], max_length=1000, null=True),
        ),
    ]
