# Generated by Django 4.1.3 on 2023-04-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds', '0064_bulletin_bulletinfile_bulletincomment_aknowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletincomment',
            name='bulletin',
        ),
        migrations.RemoveField(
            model_name='bulletinfile',
            name='bulletin',
        ),
        migrations.DeleteModel(
            name='Aknowledge',
        ),
        migrations.DeleteModel(
            name='Bulletin',
        ),
        migrations.DeleteModel(
            name='BulletinComment',
        ),
        migrations.DeleteModel(
            name='BulletinFile',
        ),
    ]
